#!/bin/sh

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch"
  exit 1
fi

FILES=$(git diff --diff-filter=rd --cached --name-only -- . ':!*.yml' ':!*.json' ':!*.txt' ':!*.gitignore' ':!hooks/pre-commit' ':!*.sh' ':!Dockerfile' | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Run pylint all selected files
pylint "$(git ls-files '*.py')" || exit 1

# Run black formatter all selected files
echo "$FILES" | xargs black

# Reset the modified/prettified files to staging
echo "$FILES" | xargs git reset

# Run automated tests
python -m pytest -vv tests/ || exit 1

# Add back the modified/prettified files to staging
echo "$FILES" | xargs git add

exit 0

